Validate zero amount in a defined activity
bitcoin-dev-project/sim-ln pull request #180
Opened 2024-04-18 08:39 UTC by joseguru

This PR addresses the issue #176 . This has been done by updating the validate_activity function 

- updated [validate_activity](https://github.com/bitcoin-dev-project/sim-ln/blob/main/sim-lib/src/lib.rs#L457) to disallow zero values.
- Throws a validation error when amount_msat is 0 on a defined activity

2024-04-22 13:04 UTC, Anyitechs requested changes
Good job on the PR @joseguru. Left a few feedbacks on having a descriptive error message, fixing the lint error and maybe having the zero amount validation after the source and destination node validation, if it makes sense to you.

cc: @carlaKC

2024-04-22 13:38 UTC, carlaKC reviewed
Agree with @Anyitechs's review here. It would be very nice to include some test coverage for `validate_activity` with this PR as well. We've been quite shocking with tests so far in the project's existence, but that's certainly something we want to change.

2024-04-23 09:04 UTC, joseguru commented on sim-lib/src/lib.rs
> +            if payment_flow.amount_msat==0 {
@Anyitechs. I see. This makes sense

2024-04-24 11:24 UTC, joseguru commented
Hello @carlaKC we were having a chat with @Anyitechs on the where to place test files. The current implementation has tests written on each file , for example defined_activity.rs has tests written on it.
Can these tests files be separated to  a tests directory then have individual test file for each implementation?

2024-05-06 19:01 UTC, carlaKC commented
> Hello @carlaKC we were having a chat with @Anyitechs on the where to place test files. The current implementation has tests written on each file , for example defined_activity.rs has tests written on it. Can these tests files be separated to a tests directory then have individual test file for each implementation?

We're following the [rust convention](https://doc.rust-lang.org/book/ch11-03-test-organization.html#unit-tests) of including tests in the same file in a different module - I don't really see a compelling reason to move them into another file?

2024-05-24 16:39 UTC, carlaKC commented
Closing due to inactivity, please feel free to re-open if you've got time to pick this up again.

2024-05-24 16:39 UTC, closed without merging

2024-05-25 06:07 UTC, joseguru commented
Hi @carlaKC Been working on it on the side . Been trying to work on mocking a Simulation as per your instructions. So it work in progress